#!/bin/sh

# Set key via environment variable.
key="$SCREENSHOT_API_KEY"
dest_path="$1"
case_url=https://www.schools.nyc.gov/school-life/health-and-wellness/covid-information/daily-covid-case-map
test_url=https://testingresults.schools.nyc/surveytesting/summary

if [ -z "$key" ]; then
  printf "Please pass your screenshotlayer API key as the first argument.\n"
  exit 1
fi

if [ -z "$dest_path" ]; then
  printf "Please pass your destination path as the second argument.\n"
  exit 1
fi
date=$(date +%Y-%m-%d)

# Cases.
wget --quiet --output-document "${dest_path}/case-${date}.png" "http://api.screenshotlayer.com/api/capture?access_key=$key&url=$case_url&viewport=1440x900&fullpage=1&force=1"
# Tests
wget --quiet --output-document "${dest_path}/test-${date}.png" "http://api.screenshotlayer.com/api/capture?access_key=$key&url=$test_url&viewport=1440x900&fullpage=1&force=1"
