name: Data processing with python scripts

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0/3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:

    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup libxml pre-reqs
      run: |
        sudo apt-get install -y libxml2-dev libxslt1-dev

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r parse/requirements.txt        
        pip install -r charts/requirements.txt        

    - name: execute parse/summary.py
      run: python parse/summary.py

#    - name: execute parse/testingresults.py
#      run: python parse/testingresults.py

    - name: execute charts/generate-cases-by-week.py
      run: python charts/generate-cases-by-week.py

    - name: execute parse/generate-cases-by-week.py
      run: python parse/generate-cases-by-week.py

    - name: execute parse/cumulative-cases-from-school-testing.py
      run: python parse/cumulative-cases-from-school-testing.py

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
